server:
  servlet:
    session:
      timeout: 30m
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.60.32:3306/phy_test
    username: g06
    password: g06
  jackson:
    serialization:
      fail-on-empty-beans: false