spring:
  application:
    name: heartbridge
  profiles:
    active: ltdz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  task:
    scheduling:
      pool:
        size: 5
  web:
    resources:
      #TODO : edit.
      static-locations: file:///E:/images, classpath:/static

logging:
  level:
    g06:
      ecnu:
        heartbridge:
          mapper: debug
          service: debug
          entity: debug
          controller: debug
    org:
      mybatis: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: g06/ecnu/heartbridge/entity
image-upload:
  path: file:///E:/images